### ISSUE TITLE
[BUG] Reroll Dialog Box UI Problem

### ISSUE THREAD

**Issue by Byroks** [Rayji96/foundry-V5#289] opened 2024-03-09 09:51 UTC
**Describe the bug**

When Rerolling, sometimes the reroll dialog box opens up smaller.

This causes a minor Issue when scrolling down, as the Reroll UI Elements don't stay atop of the boxes but also scroll down.

**To Reproduce**

1. Have a roll where you can spend willpower on
2. Open a Character sheet via Token on a scene
3. Select Willpower Reroll on the message
5. See error

**Expected behavior**
I expect the box to always spawn full size so no scrolling is needed or the UI elements to stay on top of the selected boxes/die when I scroll.

**Screenshots**
![image](https://github.com/Rayji96/foundry-V5/assets/19290311/c42a93c2-e8e8-48c3-a107-4e5c523e8893)
![image](https://github.com/Rayji96/foundry-V5/assets/19290311/0d8be5b3-e0ce-44e2-b660-64f10021a153)

**Desktop (please complete the following information):**

- Browser [Chrome]
- FoundryVTT Version [11 Build 315]
- Foundry-V5 Version [4.0.0-prerelease-2]

**Comment by Byroks** [comment] 2024-03-09 09:56
Couldn't reproduce it with prerelease3, leaving it open for validation.

**Comment by Veilza** [comment] 2024-03-09 11:28
As you've noted, this in fact would've been fixed with the willpower reroll rework in prerelease 3.

Closing this issue as I can't reproduce it on the latest dev build either, so the problem shouldn't be relevant for the upcoming stable release.

**Closed by Veilza** 2024-03-09 11:28 UTC
Labels: bug
