### ISSUE TITLE
[BUG prerelease]? How do you shift to a non-human/wolf form?

### ISSUE THREAD

**Issue by JohanFalt** [Rayji96/foundry-V5#207] opened 2023-10-29 12:21 UTC
Tried to shift from human to something else. 

You click on transform for Crinos and dice are rolling, no difference if you succeed with the right number of successes or fails.

Clicking on human or wolf shifts right away.

**Comment by daviruss** [comment] 2023-10-29 22:07
I don't think this is a bug. The way you said it seems to be working as it's expected. When you fail a Rage Check in any situation it works as expected except you loose a point in Rage and Human and Lupus forms doesn't need a check.

**Comment by JohanFalt** [comment] 2023-10-30 05:01
But I haven't found a way to set the firm to crinos e.g

**Comment by Veilza** [comment] 2023-10-30 05:36
As per the book, if you drop to 0 Rage while attempting to transform, your transformation fails. This is intended behaviour--if the actor you're using has no rage or it goes down to 0 as a result of failed Rage rolls, then it won't do anything and you will stay on whatever form you were on before.

Though I can mark this as something that needs to be more clear, in an effort to make sure it's not confusing in the future.

**Comment by JohanFalt** [comment] 2023-10-30 07:16
If you have rage it works as intended.

I would recommend that if you don't have the rage to succeed then you should get a warning for it.

So NO bug!

**Comment by Veilza** [comment] 2023-10-30 07:19
Yeap, I'll add a warning for that in the near future. I'll also make it more obvious that you can't transform when you've "Lost the Wolf" (have 0 Rage) on the actual actor sheet.

**Comment by Veilza** [comment] 2023-10-30 07:21
Closing this issue in favour of #208 to improve clarity on this feature.

**Closed by Veilza** 2023-10-30 07:21 UTC
Labels: bug
