### ISSUE TITLE
[BUG] Willpower rerolls don't roll any dice

### ISSUE THREAD

**Issue by TashaGrn** [Rayji96/foundry-V5#192] opened 2023-06-29 07:42 UTC
**Describe the bug**
When doing a willpower reroll from the chat, no dice are rolled.

**To Reproduce**

1. Go to Chat log
2. right click on the initial roll dialog and choose willpower Reroll
3. Choose any dice to reroll
4. Click OK
5. Nothing happens no dice are rolled, and no willpower is removed

**Expected behavior**
I expect the number of dice to roll

**Screenshots**

**Desktop (please complete the following information):**

- Browser [Safari, Firefox (Mac and Windows), Chrome (MacOS and Windows]

- Foundry-V10 Version patch 7 (Build 303)
- Foundry-V10 Version patch 6 (Build 291)

**Additional context**

**Comment by CoridanM** [comment] 2023-07-03 20:49
Try updating to Foundry V11. It works fine for me there.

**Comment by Rayji96** [comment] 2023-07-30 00:39
Cannot reproduce, closing since it's more than a month old

**Closed by Rayji96** 2023-07-30 00:39 UTC
Labels: bug
